// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAELOcgVj0eZyO2TZi8i_YMmS3_yC_6CrQ',
    appId: '1:743635869733:web:982a7aa3287c17aa411fcc',
    messagingSenderId: '743635869733',
    projectId: 'Family-hub-6a773',
    authDomain: 'Family-hub-6a773.firebaseapp.com',
    storageBucket: 'Family-hub-6a773.firebasestorage.app',
    measurementId: 'G-44FH2SXF8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx8VmV1dNKjVo7qYIjsiqol_sSq-I-WkU',
    appId: '1:743635869733:android:4102327fbb40e50b411fcc',
    messagingSenderId: '743635869733',
    projectId: 'Family-hub-6a773',
    storageBucket: 'Family-hub-6a773.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH9jPraZkwo5k5VZkYFxmcaqcp2Znz-yE',
    appId: '1:743635869733:ios:f80a94b9951ad33f411fcc',
    messagingSenderId: '743635869733',
    projectId: 'Family-hub-6a773',
    storageBucket: 'Family-hub-6a773.firebasestorage.app',
    iosBundleId: 'com.example.familyHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH9jPraZkwo5k5VZkYFxmcaqcp2Znz-yE',
    appId: '1:743635869733:ios:f80a94b9951ad33f411fcc',
    messagingSenderId: '743635869733',
    projectId: 'Family-hub-6a773',
    storageBucket: 'Family-hub-6a773.firebasestorage.app',
    iosBundleId: 'com.example.familyHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAELOcgVj0eZyO2TZi8i_YMmS3_yC_6CrQ',
    appId: '1:743635869733:web:053e65387a3f4161411fcc',
    messagingSenderId: '743635869733',
    projectId: 'Family-hub-6a773',
    authDomain: 'Family-hub-6a773.firebaseapp.com',
    storageBucket: 'Family-hub-6a773.firebasestorage.app',
    measurementId: 'G-T88FSS23ZB',
  );
}
